# Logo (Font Awesome Class)
fa_logo: fa-terminal

# Header
menu:
  Home: /
  About: /about/
  Games: https://games.thedrowsy.com
  Projects: /projects/
  Archives: /archives/

# Default post title
default_post_title: Error, Title not assigned

# Archive Date Format
archive_date_format: MMM DD, YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
#twitter_url: https://twitter.com/?lang=en
#facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/someoriginalusername1/
#dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/bcat1023
#telegram_url: https://telegram.org/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: bthecat984@outlook.com
#rss_url: \#

# Footer About Text
footer_about: "Welcome to thedrowsy.com, feel free to explore and look around and try out a few of my projects"

# Footer Copyright Line
footer_copyright: "@2022. All right reserved | Powered by Netlify, Hexo, Alpha Dust, and Cloudflare"

